[package]
name = "trace-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.1"
indicatif = { version = "0.17.8", features = ["rayon"] }
itertools = "0.13.0"
rand = "0.8.5"
rayon = "1.10.0"
